version: '3.8'

services:
  app:
    image: nagulregistery.azurecr.io/images/web-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: "postgresql+psycopg2://postgres:postgres@db:5432/NagulShop_BBY"

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: NagulShop_BBY
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
