version: '3.8'

services:
  cli:
    image: nagulshop-cli:1.0.0
    stdin_open: true
    depends_on:
      - app
    environment:
      API_URL: "http://app:80"
  app:
    image: nagulshop_app:1.0.0
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_URL: "postgresql+psycopg2://postgres:postgres@db:5432/postgres"

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
